# Qserv operator CI workflow
---
name: "e2e tests"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Run Harbor demo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Required by ciux
        with:
          fetch-depth: 0
      - name: Stop apparmor
        run: |
          sudo /etc/init.d/apparmor stop
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Install and run ciux
        run: |
          ./ignite.sh
      - name: Create k8s/kind cluster
        run: |
          ./prereq.sh
      - name: Install nginx-controller
        run: |
          ./install_nginx.sh
      - name: Install harbor
        run: |
          ./install_harbor.sh
